name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install LLVM
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm

      - name: Build and Test
        run: |
          cmake .
          make