name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install LLVM
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm

      - name: Build and Test
        run: |
          cmake .
          make

      - name: Run Tests
        run: |
          ./compiler ../output.txt
          actual_result=$(tail -n 1 output.txt)
          expected_result="5"
          if [ "$actual_result" == "$expected_result" ]; then
            echo "Test Passed!"
          else
            echo "Test Failed! Expected: $expected_result, Actual: $actual_result"
            exit 1
          fi