name: Docker Build Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          dockerfile: Dockerfile
          context: .

      - name: Build Docker Image
        run: docker build -t my_project .

      - name: Display Docker Images
        run: docker images

      - name: Run Docker Container (Optional)
        run: docker run my_project

      - name: Clean Up Docker Resources (Optional)
        run: docker rmi my_project